In [1]:
#PCA with scaling

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

features = pd.read_csv("features.csv")
labels = pd.read_csv("labels.csv")

scaled_features = StandardScaler().fit_transform(features)
pca = PCA(.99)
pca.fit(scaled_features)
reduced_features = pca.transform(scaled_features)
print(pca.explained_variance_ratio_)
print(features.shape)
print(reduced_features.shape)
pd.DataFrame(reduced_features).to_csv("reduced_features.csv", index=False)

[0.3275794  0.1257762  0.10568402 0.05863195 0.04475674 0.03361112
 0.03214146 0.02888541 0.02843898 0.02562268 0.02502078 0.02301277
 0.02105718 0.01952697 0.0158941  0.01574302 0.0137743  0.0116017
 0.00948355 0.0081536  0.00686005 0.00419308 0.00336021 0.00319655]
(1192, 38)
(1192, 24)


In [2]:
#PCA without scaling

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

features = pd.read_csv("features.csv")
labels = pd.read_csv("labels.csv")

pca = PCA(.99)
pca.fit(features)
reduced_features = pca.transform(features)
print(pca.explained_variance_ratio_)
print(features.shape)
print(reduced_features.shape)
pd.DataFrame(reduced_features).to_csv("reduced_features.csv", index=False)


[0.98562937 0.00987983]
(1192, 38)
(1192, 2)


In [3]:
import matplotlib.pyplot as plt
noscalePCA = pd.DataFrame(reduced_features)
fig, ax = plt.subplots()
ax.scatter(noscalePCA.iloc[:,0],noscalePCA.iloc[:,1])

In [4]:
df = pd.read_csv("standard_train_features.csv")

In [5]:
print(df.shape)
df.head()

(834, 38)


Year       Age        Ht        Wt       BMI         G        GS  \
0  1.196638  0.645551  1.189409  1.448029  0.706525  0.923466  1.005274   
1  1.403992 -0.561060 -1.352467 -0.298236  0.778252  0.461179  0.623837   
2 -0.358519  0.645551  0.553940 -0.222311 -0.728026 -0.925683 -0.711192   
3  1.092961  1.610840  0.553940  0.309160 -0.082478  0.923466  1.005274   
4 -0.151165  2.093484  1.189409  1.068406  0.276160  0.923466  1.005274   

        Cmp       Att      Cmp%  ...       GWD     Att.1     Yds.2     Y/A.1  \
0  1.533850  1.375902  0.986836  ...  0.886266 -0.177352 -0.186413  0.064312   
1  0.321464  0.195808  0.893421  ...  0.211863  3.270778  3.246480  0.982442   
2 -1.036772 -1.024779 -0.631178  ... -0.462540 -1.028189 -0.896414 -1.689880   
3  1.770858  1.682495  0.764755  ...  0.211863 -0.356475 -0.676826 -1.105149   
4  1.105413  1.410611 -0.532476  ...  1.560670 -0.266914 -0.676826 -1.161571   

       TD.1     Y/G.1       2PM       Pts        PB       AP1  
0 -0.126348 -0.398269 -0.233451 -0.144373 -0.496625 -0.156748  
1  1.639706  3.178560  3.660515  1.789876  2.013590 -0.156748  
2 -0.715033 -1.011737 -0.233451 -0.724647 -0.496625 -0.156748  
3  1.639706 -0.834975 -0.233451  1.596451  2.013590 -0.156748  
4 -0.715033 -0.834975 -0.233451 -0.724647 -0.496625 -0.156748  

[5 rows x 38 columns]

In [6]:
del df["ANY/A"]
del df["AY/A"]

In [7]:
scaled_features = StandardScaler().fit_transform(df)
scaled = pd.DataFrame(scaled_features)
print(df.shape)
print(scaled.shape)
scaled.columns = df.columns

(834, 36)
(834, 36)


In [8]:
pca = PCA(.99)
pca.fit(scaled_features)
reduced_features = pca.transform(scaled_features)
print(pca.explained_variance_ratio_)
print(df.shape)
print(reduced_features.shape)

[0.32531316 0.11927145 0.09812393 0.06288181 0.04378062 0.03570558
 0.0346883  0.02990814 0.0287064  0.02708341 0.02602653 0.02412006
 0.02152339 0.02070228 0.01625768 0.01584561 0.01420071 0.01170538
 0.01024212 0.00823128 0.00656947 0.00441451 0.0035734  0.00301649]
(834, 36)
(834, 24)


In [9]:
import numpy as np
n_pcs = pca.components_.shape[0]
most_important = [np.abs(pca.components_[i]).argmax() for i in range(n_pcs)]
values = [np.abs(pca.components_[i]).max() for i in range(n_pcs)]
feature_names = scaled.columns
most_important_names = [feature_names[most_important[i]] for i in range(n_pcs)]
dic = {'PC{}'.format(i): most_important_names[i] for i in range(n_pcs)}
df = pd.DataFrame(dic.items())

In [10]:
df["Value"] = values
df["Explained Variance"] = pca.explained_variance_ratio_

In [11]:
df = df.rename(columns={0:"PC",1:"Feature"})

In [12]:
df = df[["PC","Explained Variance","Feature","Value"]]

In [13]:
df

PC  Explained Variance Feature     Value
0    PC0            0.325313     Yds  0.280911
1    PC1            0.119271   Y/G.1  0.393854
2    PC2            0.098124    Rate  0.348222
3    PC3            0.062882      Wt  0.580897
4    PC4            0.043781     Sk%  0.348318
5    PC5            0.035706     4QC  0.401723
6    PC6            0.034688      Ht  0.471126
7    PC7            0.029908     4QC  0.337127
8    PC8            0.028706     AP1  0.399842
9    PC9            0.027083       T  0.902926
10  PC10            0.026027     2PM  0.604933
11  PC11            0.024120     2PM  0.608965
12  PC12            0.021523     Age  0.563960
13  PC13            0.020702     AP1  0.503733
14  PC14            0.016258      PB  0.607680
15  PC15            0.015846   Pick6  0.598300
16  PC16            0.014201     Y/G  0.525070
17  PC17            0.011705     TD%  0.503293
18  PC18            0.010242   Y/A.1  0.485901
19  PC19            0.008231       L  0.476642
20  PC20            0.006569     Y/A  0.615434
21  PC21            0.004415     Sk%  0.552546
22  PC22            0.003573     GWD  0.731483
23  PC23            0.003016     Int  0.748152

In [29]:
top3 = [np.abs(pca.components_[i]).argsort()[-3:] for i in range(n_pcs)]
#[pca.components_[i][top3][i] for i in range(n_pcs)]
top3[0]

8

(834, 24)

In [19]:
print(reduced_features.shape)
print(labels.shape)

(834, 24)
(1192, 1)


In [22]:
df_txt = pd.read_csv("standard_features.txt")
labels = pd.read_csv("labels.csv")
print(df_txt.shape)
print(labels.shape)

(1192, 36)
(1192, 1)


In [84]:
nextYear_winRange = []
#print(labels.shape[0])
for i in range(labels.shape[0]):
    if labels.iloc[i,0] <= 3:
        nextYear_winRange.append("0-3")
    elif labels.iloc[i,0] <= 6:
        nextYear_winRange.append("4-6")
    elif labels.iloc[i,0] <= 9:
        nextYear_winRange.append("7-9")
    elif labels.iloc[i,0] <= 12:
        nextYear_winRange.append("10-12")
    else:
        nextYear_winRange.append("13-16")
        

In [85]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest = train_test_split(df_txt,nextYear_winRange,test_size=0.3)

In [86]:
scaled_features = StandardScaler()
train_scaled = scaled_features.fit_transform(Xtrain)
scaled = pd.DataFrame(train_scaled)
print(Xtrain.shape)
print(scaled.shape)
scaled.columns = Xtrain.columns

(834, 36)
(834, 36)


In [87]:
pca = PCA(.99)
pca.fit(scaled)
reduced_features = pca.transform(scaled)
print(pca.explained_variance_ratio_)
print(Xtrain.shape)
print(reduced_features.shape)

[0.32861636 0.11897019 0.09565287 0.06069323 0.04445337 0.03619183
 0.03449914 0.03065506 0.02807856 0.02800543 0.02604137 0.02359005
 0.02213493 0.01986712 0.01661837 0.01565268 0.01417334 0.01188874
 0.00990377 0.00876221 0.00657995 0.00416581 0.00345488 0.00318717]
(834, 36)
(834, 24)


In [88]:
test_scaled = pd.DataFrame(scaled_features.transform(Xtest))
test_scaled.columns = Xtest.columns
reduced_test_features = pca.transform(test_scaled)
print(Xtest.shape)
print(reduced_test_features.shape)

(358, 36)
(358, 24)


## Supervised Section

In [89]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [101]:
lr = LogisticRegression()
lr.fit(reduced_features,ytrain)
ytrain_predict = lr.predict(reduced_features)
print("Train Accuracy: {}".format(accuracy_score(ytrain,ytrain_predict)))
ytest_predict = lr.predict(reduced_test_features)
print("Test Accuracy: {}".format(accuracy_score(ytest,ytest_predict)))

probabilities = lr.predict_proba(reduced_features)
print(probabilities[0:5])
np.average(probabilities,axis=0)

Train Accuracy: 0.4616306954436451
Test Accuracy: 0.4692737430167598
[[0.3082983  0.18303664 0.01585997 0.23314888 0.2596562 ]
 [0.46241561 0.11648309 0.03653682 0.18620628 0.19835821]
 [0.53198338 0.19365746 0.00481827 0.21141249 0.05812841]
 [0.41918465 0.15387839 0.02135758 0.21212022 0.19345916]
 [0.56078304 0.02570133 0.02899412 0.24937489 0.13514662]]


array([0.37410117, 0.14388163, 0.04436189, 0.19904237, 0.23861295])

### Not Good

In [102]:
nextYear_winRange = []
#print(labels.shape[0])
for i in range(labels.shape[0]):
    if labels.iloc[i,0] <= 4:
        nextYear_winRange.append("0-4")
    elif labels.iloc[i,0] <= 8:
        nextYear_winRange.append("5-8")
    elif labels.iloc[i,0] <= 12:
        nextYear_winRange.append("9-12")
    else:
        nextYear_winRange.append("13-16")

Xtrain,Xtest,ytrain,ytest = train_test_split(df_txt,nextYear_winRange,test_size=0.3)

scaled_features = StandardScaler()
train_scaled = scaled_features.fit_transform(Xtrain)
scaled = pd.DataFrame(train_scaled)
print(Xtrain.shape)
print(scaled.shape)
scaled.columns = Xtrain.columns

pca = PCA(.99)
pca.fit(scaled)
reduced_features = pca.transform(scaled)
print(pca.explained_variance_ratio_)
print(Xtrain.shape)
print(reduced_features.shape)

test_scaled = pd.DataFrame(scaled_features.transform(Xtest))
test_scaled.columns = Xtest.columns
reduced_test_features = pca.transform(test_scaled)
print(Xtest.shape)
print(reduced_test_features.shape)

(834, 36)
(834, 36)
[0.32340509 0.11507412 0.10100924 0.06421699 0.04705574 0.03566075
 0.03206222 0.03042106 0.02885474 0.02792907 0.02677767 0.02371951
 0.0217271  0.01980141 0.01684516 0.01529032 0.01376286 0.0125159
 0.00987918 0.00831969 0.00654896 0.00406505 0.00364068 0.00321312]
(834, 36)
(834, 24)
(358, 36)
(358, 24)


In [103]:
lr = LogisticRegression()
lr.fit(reduced_features,ytrain)
ytrain_predict = lr.predict(reduced_features)
print("Train Accuracy: {}".format(accuracy_score(ytrain,ytrain_predict)))
ytest_predict = lr.predict(reduced_test_features)
print("Test Accuracy: {}".format(accuracy_score(ytest,ytest_predict)))

probabilities = lr.predict_proba(reduced_features)
print(probabilities[0:5])
np.average(probabilities,axis=0)

Train Accuracy: 0.5539568345323741
Test Accuracy: 0.4972067039106145
[[0.57883464 0.00412978 0.2777807  0.13925488]
 [0.84879424 0.00481531 0.12889601 0.01749445]
 [0.76119588 0.00691808 0.17787418 0.05401185]
 [0.52415682 0.00825138 0.33209789 0.13549391]
 [0.8907782  0.00453653 0.09560463 0.00908065]]


array([0.4628299 , 0.03596993, 0.29856076, 0.20263941])

### Also Not Good

In [104]:
nextYear_winRange = []
#print(labels.shape[0])
for i in range(labels.shape[0]):
    if labels.iloc[i,0] <= 5:
        nextYear_winRange.append("0-5")
    elif labels.iloc[i,0] <= 10:
        nextYear_winRange.append("6-10")
    else:
        nextYear_winRange.append("11-16")

Xtrain,Xtest,ytrain,ytest = train_test_split(df_txt,nextYear_winRange,test_size=0.3)

scaled_features = StandardScaler()
train_scaled = scaled_features.fit_transform(Xtrain)
scaled = pd.DataFrame(train_scaled)
print(Xtrain.shape)
print(scaled.shape)
scaled.columns = Xtrain.columns

pca = PCA(.99)
pca.fit(scaled)
reduced_features = pca.transform(scaled)
print(pca.explained_variance_ratio_)
print(Xtrain.shape)
print(reduced_features.shape)

test_scaled = pd.DataFrame(scaled_features.transform(Xtest))
test_scaled.columns = Xtest.columns
reduced_test_features = pca.transform(test_scaled)
print(Xtest.shape)
print(reduced_test_features.shape)

(834, 36)
(834, 36)
[0.32568109 0.11916829 0.09928878 0.06228238 0.04385884 0.03590421
 0.03239378 0.03028264 0.02926801 0.02750678 0.02596957 0.02358037
 0.02111127 0.02068198 0.01790245 0.01604645 0.01394919 0.012116
 0.00960936 0.00828987 0.00629399 0.00441116 0.00333233 0.00316978]
(834, 36)
(834, 24)
(358, 36)
(358, 24)


In [105]:
lr = LogisticRegression()
lr.fit(reduced_features,ytrain)
ytrain_predict = lr.predict(reduced_features)
print("Train Accuracy: {}".format(accuracy_score(ytrain,ytrain_predict)))
ytest_predict = lr.predict(reduced_test_features)
print("Test Accuracy: {}".format(accuracy_score(ytest,ytest_predict)))

probabilities = lr.predict_proba(reduced_features)
print(probabilities[0:5])
np.average(probabilities,axis=0)

Train Accuracy: 0.6235011990407674
Test Accuracy: 0.6564245810055865
[[0.73412622 0.04118301 0.22469077]
 [0.50893915 0.07933101 0.41172985]
 [0.20305932 0.36849638 0.4284443 ]
 [0.25001646 0.43424418 0.31573936]
 [0.42541878 0.12527408 0.44930714]]


array([0.50239597, 0.13188479, 0.36571924])

In [106]:
nextYear_winRange = []
#print(labels.shape[0])
for i in range(labels.shape[0]):
    if labels.iloc[i,0] <= 8:
        nextYear_winRange.append("0-8")
    else:
        nextYear_winRange.append("9-16")

Xtrain,Xtest,ytrain,ytest = train_test_split(df_txt,nextYear_winRange,test_size=0.3)

scaled_features = StandardScaler()
train_scaled = scaled_features.fit_transform(Xtrain)
scaled = pd.DataFrame(train_scaled)
print(Xtrain.shape)
print(scaled.shape)
scaled.columns = Xtrain.columns

pca = PCA(.99)
pca.fit(scaled)
reduced_features = pca.transform(scaled)
print(pca.explained_variance_ratio_)
print(Xtrain.shape)
print(reduced_features.shape)

test_scaled = pd.DataFrame(scaled_features.transform(Xtest))
test_scaled.columns = Xtest.columns
reduced_test_features = pca.transform(test_scaled)
print(Xtest.shape)
print(reduced_test_features.shape)

(834, 36)
(834, 36)
[0.32820333 0.11277439 0.09720574 0.06146014 0.04523405 0.03663038
 0.03263163 0.03144714 0.02836803 0.02711706 0.02606013 0.0247754
 0.02156359 0.02097965 0.01727126 0.01671146 0.01451206 0.01245486
 0.01012419 0.00850527 0.00644246 0.00444572 0.00336286 0.0032751 ]
(834, 36)
(834, 24)
(358, 36)
(358, 24)


In [107]:
lr = LogisticRegression()
lr.fit(reduced_features,ytrain)
ytrain_predict = lr.predict(reduced_features)
print("Train Accuracy: {}".format(accuracy_score(ytrain,ytrain_predict)))
ytest_predict = lr.predict(reduced_test_features)
print("Test Accuracy: {}".format(accuracy_score(ytest,ytest_predict)))

probabilities = lr.predict_proba(reduced_features)
print(probabilities[0:5])
np.average(probabilities,axis=0)

Train Accuracy: 0.7709832134292566
Test Accuracy: 0.7430167597765364
[[0.82901065 0.17098935]
 [0.90366597 0.09633403]
 [0.91546558 0.08453442]
 [0.88413477 0.11586523]
 [0.90011962 0.09988038]]


array([0.76019248, 0.23980752])